### PR TITLE
add queue and stack tests

### PR DESCRIPTION
**Pull request by ahmetbcakici**

### CODE REVIEW

**Comment by jrasmusson** [comment]
Hi @ahmetbcakici - thank you for the PR.

Can you add back the `algorithms.iml` file you deleted? I get warning when I open intelliJ without it.

Once you do I can merge this PR. Thank you. Jonathan

**Comment by ahmetbcakici** [comment]
Thanks for warning, it should've happened accidently. I added.

**Comment by ahmetbcakici** [comment]
Thanks for warning, it should've happened accidently. I added. @jrasmusson

**Comment by jrasmusson** [comment]
Thanks for the tests!

**Pull request merged**
